In [7]:
import plotly.express as px

import pandas as pd
df = pd.read_excel('C:/Users/WTK Agro/Desktop/Pareceres/Concluído/Em análise/ZR ATACADISTA E DISTRIBUIDOR LTDA/1.xlsx')

df.head()

,"Tabela 6903 - Índice de Preços ao Produtor, por tipo de índice, indústria geral, indústrias extrativas e indústrias de transformação e atividades (dezembro de 2018 = 100)",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47
0,Variável - IPP - Número-índice (dezembro de 20...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,"Indústria geral, indústrias extrativas e indús...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Indústria Geral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,janeiro 2018,fevereiro 2018,março 2018,abril 2018,maio 2018,junho 2018,julho 2018,agosto 2018,setembro 2018,...,fevereiro 2021,março 2021,abril 2021,maio 2021,junho 2021,julho 2021,agosto 2021,setembro 2021,outubro 2021,novembro 2021
4,Brasil,91.63578,91.98513,92.97477,94.44519,96.85567,99.05379,100.17143,101.03231,103.96787,...,136.73626,143.0612,146.19508,147.63531,149.54092,152.31924,155.1925,155.58802,159.10043,161.1899

In [10]:
df.loc[df[‘Tabela 6903 - Índice de Preços ao Produtor, por tipo de índice, indústria geral, indústrias extrativas e indústrias de transformacao e atividades (dezembro de 2018 = 100)’] =='Brasil']

SyntaxError: invalid character in identifier (<ipython-input-10-0bcf9645496f>, line 1)